"""empty message

Revision ID: 04a24e7ccca0
Revises: 333258463481
Create Date: 2023-11-25 02:49:36.685043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a24e7ccca0'
down_revision = '333258463481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mixproduto_produto_ibfk_1', 'mixproduto_produto', type_='foreignkey')
    op.drop_constraint('mixproduto_produto_ibfk_2', 'mixproduto_produto', type_='foreignkey')
    op.create_foreign_key(None, 'mixproduto_produto', 'mixproduto', ['mixproduto_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'mixproduto_produto', 'produto', ['produto_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mixproduto_produto', type_='foreignkey')
    op.drop_constraint(None, 'mixproduto_produto', type_='foreignkey')
    op.create_foreign_key('mixproduto_produto_ibfk_2', 'mixproduto_produto', 'produto', ['produto_id'], ['id'])
    op.create_foreign_key('mixproduto_produto_ibfk_1', 'mixproduto_produto', 'mixproduto', ['mixproduto_id'], ['id'])
    # ### end Alembic commands ###
