"""empty message

Revision ID: 076690c60c9a
Revises: ca648867e6b0
Create Date: 2023-11-04 01:57:03.217666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '076690c60c9a'
down_revision = 'ca648867e6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mixproduto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cod_prod_mix', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=False),
    sa.Column('cadastrado_em', sa.Date(), nullable=False),
    sa.Column('atualizado_em', sa.Date(), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('filial_id', sa.Integer(), nullable=False),
    sa.Column('pedidosprod_id', sa.Integer(), nullable=False),
    sa.Column('producao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filial_id'], ['filial.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedidosprod_id'], ['pedidoproducao.id'], ),
    sa.ForeignKeyConstraint(['producao_id'], ['producao.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mixproduto_filial',
    sa.Column('mixproduto_id', sa.Integer(), nullable=False),
    sa.Column('filial_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filial.id'], ),
    sa.ForeignKeyConstraint(['mixproduto_id'], ['mixproduto.id'], ),
    sa.PrimaryKeyConstraint('mixproduto_id', 'filial_id')
    )
    op.add_column('producao', sa.Column('usuario_id', sa.Integer(), sa.ForeignKey('usuario.id'), nullable=False))
    op.add_column('producao', sa.Column('pedidosprod_id', sa.Integer(), nullable=False))
    op.drop_constraint('producao_ibfk_3', 'producao', type_='foreignkey')
    op.create_foreign_key(None, 'producao', 'pedidoproducao', ['pedidosprod_id'], ['id'])
    op.create_foreign_key(None, 'producao', 'mixproduto', ['mixproduto_id'], ['id'])
    op.create_foreign_key(None, 'producao', 'usuario', ['usuario_id'], ['id'])
    op.drop_column('producao', 'pedidoproducao_id')
    op.drop_constraint('usuario_ibfk_3', 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'producao_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('producao_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('usuario_ibfk_3', 'usuario', 'producao', ['producao_id'], ['id'])
    op.add_column('producao', sa.Column('pedidoproducao_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'producao', type_='foreignkey')
    op.drop_constraint(None, 'producao', type_='foreignkey')
    op.drop_constraint(None, 'producao', type_='foreignkey')
    op.create_foreign_key('producao_ibfk_3', 'producao', 'pedidoproducao', ['pedidoproducao_id'], ['id'])
    op.drop_column('producao', 'pedidosprod_id')
    op.drop_column('producao', 'usuario_id')
    op.drop_table('mixproduto_filial')
    op.drop_table('mixproduto')
    # ### end Alembic commands ###
