"""empty message

Revision ID: 0f0d1001e4df
Revises: 6ab84f65d843
Create Date: 2023-11-23 11:24:49.350018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f0d1001e4df'
down_revision = '6ab84f65d843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quantidade_mix_produtos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quantidade_mix_produtos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mix_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mix_id'], ['mixproduto.id'], name='quantidade_mix_produtos_ibfk_1'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name='quantidade_mix_produtos_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
