"""empty message

Revision ID: 15784abe3176
Revises: 18af1816234e
Create Date: 2023-08-28 02:29:01.378945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15784abe3176'
down_revision = '18af1816234e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidoproducao', 'data_pedido',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidoproducao', 'data_pedido',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
