"""empty message

Revision ID: 18af1816234e
Revises: 6b528bebf59e
Create Date: 2023-08-26 02:10:13.125021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18af1816234e'
down_revision = '6b528bebf59e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedido', 'data_pedido',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('pedido', 'obs',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedido', 'obs',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('pedido', 'data_pedido',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
