"""empty message

Revision ID: 1ef2751e2c15
Revises: 46a9765eb2ad
Create Date: 2023-11-19 01:01:32.341904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef2751e2c15'
down_revision = '46a9765eb2ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mixproduto_filial',
    sa.Column('mixproduto_id', sa.Integer(), nullable=False),
    sa.Column('filial_id', sa.Integer(), nullable=False),
    sa.Column('qtde_produzida', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filial_id'], ['filial.id'], ),
    sa.ForeignKeyConstraint(['mixproduto_id'], ['mixproduto.id'], ),
    sa.PrimaryKeyConstraint('mixproduto_id', 'filial_id')
    )
    op.add_column('filial', sa.Column('mixproduto', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'filial', 'mixproduto', ['mixproduto'], ['id'])
    op.add_column('mixproduto', sa.Column('filial_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mixproduto', 'filial', ['filial_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mixproduto', type_='foreignkey')
    op.drop_column('mixproduto', 'filial_id')
    op.drop_constraint(None, 'filial', type_='foreignkey')
    op.drop_column('filial', 'mixproduto')
    op.drop_table('mixproduto_filial')
    # ### end Alembic commands ###
