"""empty message

Revision ID: 20b3cd41c17b
Revises: 38601536d11a
Create Date: 2023-11-22 15:58:52.711975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b3cd41c17b'
down_revision = '38601536d11a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mixproduto_ibfk_3', 'mixproduto', type_='foreignkey')
    op.create_foreign_key(None, 'mixproduto', 'producao', ['producao_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mixproduto', type_='foreignkey')
    op.create_foreign_key('mixproduto_ibfk_3', 'mixproduto', 'producao', ['producao_id'], ['id'])
    # ### end Alembic commands ###
