"""empty message

Revision ID: 20c49575539e
Revises: a540b10ce09b
Create Date: 2023-10-11 23:56:06.623557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c49575539e'
down_revision = 'a540b10ce09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receita_cliente',
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ),
    sa.PrimaryKeyConstraint('receita_id', 'cliente_id')
    )
    op.add_column('cliente', sa.Column('receita', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cliente', 'receita', ['receita'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cliente', type_='foreignkey')
    op.drop_column('cliente', 'receita')
    op.drop_table('receita_cliente')
    # ### end Alembic commands ###
