"""empty message

Revision ID: 23bd11214090
Revises: 71bc97738772
Create Date: 2023-11-19 01:35:06.773313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23bd11214090'
down_revision = '71bc97738772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filial', 'mixproduto_id')
    op.drop_column('filial', 'mixproduto')
    op.add_column('mixproduto', sa.Column('filial_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mixproduto', 'filial', ['filial_id'], ['id'], ondelete='CASCADE')
    op.alter_column('quantidade_mix_produtos', 'produto_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('quantidade_mix_produtos', 'mix_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quantidade_mix_produtos', 'mix_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('quantidade_mix_produtos', 'produto_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'mixproduto', type_='foreignkey')
    op.drop_column('mixproduto', 'filial_id')
    op.add_column('filial', sa.Column('mixproduto', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('filial', sa.Column('mixproduto_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
