"""empty message

Revision ID: 27b44cd00888
Revises: c40637b5292f
Create Date: 2023-08-07 23:52:18.208294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b44cd00888'
down_revision = 'c40637b5292f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidoproducao', sa.Column('qtde_pedido', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidoproducao', 'qtde_pedido')
    # ### end Alembic commands ###
