"""empty message

Revision ID: 297089e43cca
Revises: a731ed8b2349
Create Date: 2023-11-25 23:18:03.205196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '297089e43cca'
down_revision = 'a731ed8b2349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido_cliente',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('pedido_id', 'cliente_id')
    )
    op.create_table('pedido_fornecedor',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('pedido_id', 'fornecedor_id')
    )
    op.create_table('pedido_produto',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('pedido_id', 'produto_id')
    )
    op.drop_index('produto_id', table_name='pedido')
    op.drop_constraint('pedido_ibfk_1', 'pedido', type_='foreignkey')
    op.drop_constraint('pedido_ibfk_3', 'pedido', type_='foreignkey')
    op.drop_constraint('pedido_ibfk_2', 'pedido', type_='foreignkey')
    op.drop_column('pedido', 'fornecedor_id')
    op.drop_column('pedido', 'cliente_id')
    op.drop_column('pedido', 'produto_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pedido', sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pedido', sa.Column('fornecedor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pedido_ibfk_2', 'pedido', 'fornecedor', ['fornecedor_id'], ['id'])
    op.create_foreign_key('pedido_ibfk_3', 'pedido', 'produto', ['produto_id'], ['id'])
    op.create_foreign_key('pedido_ibfk_1', 'pedido', 'cliente', ['cliente_id'], ['id'])
    op.create_index('produto_id', 'pedido', ['produto_id'], unique=False)
    op.drop_table('pedido_produto')
    op.drop_table('pedido_fornecedor')
    op.drop_table('pedido_cliente')
    # ### end Alembic commands ###
