"""empty message

Revision ID: 306bf02e328d
Revises: 1ef2751e2c15
Create Date: 2023-11-19 01:02:47.201432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '306bf02e328d'
down_revision = '1ef2751e2c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'filial', 'mixproduto', ['mixproduto'], ['id'])
    op.add_column('mixproduto', sa.Column('filial_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mixproduto', 'filial', ['filial_id'], ['id'], ondelete='CASCADE')
    op.alter_column('quantidade_mix_produtos', 'produto_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('quantidade_mix_produtos', 'mix_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quantidade_mix_produtos', 'mix_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('quantidade_mix_produtos', 'produto_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'mixproduto', type_='foreignkey')
    op.drop_column('mixproduto', 'filial_id')
    op.drop_constraint(None, 'filial', type_='foreignkey')
    # ### end Alembic commands ###
