"""empty message

Revision ID: 333258463481
Revises: 0f0d1001e4df
Create Date: 2023-11-24 21:45:04.628363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333258463481'
down_revision = '0f0d1001e4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quantidade_mix_produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('mix_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['mix_id'], ['mixproduto.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quantidade_mix_produtos')
    # ### end Alembic commands ###
