"""empty message

Revision ID: 338cfdbda80a
Revises: 7bf4f9f29846
Create Date: 2023-11-09 10:28:45.777597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '338cfdbda80a'
down_revision = '7bf4f9f29846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mixproduto_ibfk_2', 'mixproduto', type_='foreignkey')
    op.drop_column('mixproduto', 'pedidosprod_id')
    op.add_column('pedidoproducao', sa.Column('mixproduto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pedidoproducao', 'mixproduto', ['mixproduto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedidoproducao', type_='foreignkey')
    op.drop_column('pedidoproducao', 'mixproduto_id')
    op.add_column('mixproduto', sa.Column('pedidosprod_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('mixproduto_ibfk_2', 'mixproduto', 'pedidoproducao', ['pedidosprod_id'], ['id'])
    # ### end Alembic commands ###
