"""empty message

Revision ID: 3426b47f968c
Revises: 
Create Date: 2023-07-31 23:56:40.123754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3426b47f968c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('endereco', sa.String(length=150), nullable=False),
    sa.Column('bairro', sa.String(length=20), nullable=False),
    sa.Column('cidade', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('responsavel', sa.String(length=50), nullable=False),
    sa.Column('whatsapp', sa.String(length=50), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('endereco', sa.String(length=150), nullable=False),
    sa.Column('bairro', sa.String(length=20), nullable=False),
    sa.Column('cidade', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('responsavel', sa.String(length=50), nullable=False),
    sa.Column('whatsapp', sa.String(length=50), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('endereco', sa.String(length=150), nullable=False),
    sa.Column('bairro', sa.String(length=20), nullable=False),
    sa.Column('cidade', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('responsavel', sa.String(length=50), nullable=False),
    sa.Column('whatsapp', sa.String(length=50), nullable=False),
    sa.Column('cnpj', sa.String(length=17), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('filial_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('compra_unid', sa.Integer(), nullable=False),
    sa.Column('peso_pcte', sa.Float(precision=5, asdecimal=3), nullable=False),
    sa.Column('valor', sa.REAL(), nullable=False),
    sa.Column('custo_ultima_compra', sa.Float(), nullable=False),
    sa.Column('whatsapp', sa.String(length=50), nullable=False),
    sa.Column('qrcode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('valor_ultima_compra', sa.Float(), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=True),
    sa.Column('quantidade_minima', sa.Integer(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=True),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.String(length=80), nullable=True),
    sa.Column('obs', sa.String(length=120), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mixproduto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cod_prod_mix', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('modo_preparo', sa.Text(), nullable=False),
    sa.Column('departamento', sa.String(length=20), nullable=False),
    sa.Column('rend_kg', sa.Float(), nullable=False),
    sa.Column('rend_unid', sa.Float(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('cadastrado_em', sa.Date(), nullable=False),
    sa.Column('atualizado_em', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receita',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao_mix', sa.Text(), nullable=False),
    sa.Column('modo_preparo', sa.Text(), nullable=False),
    sa.Column('departamento', sa.String(length=50), nullable=False),
    sa.Column('rend_kg', sa.Float(), nullable=False),
    sa.Column('rend_unid', sa.Float(), nullable=False),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('api_key', sa.String(length=100), nullable=True),
    sa.Column('empresa', sa.Integer(), nullable=True),
    sa.Column('cargo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cargo'], ['funcao.id'], ),
    sa.ForeignKeyConstraint(['empresa'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.String(length=50), nullable=False),
    sa.Column('produto_id', sa.String(length=100), nullable=False),
    sa.Column('qtde', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PedCompraentra', 'PedProducaosai', name='tipoenum'), nullable=False),
    sa.Column('estoque_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estoque_id'], ['estoque.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receita_filial',
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('filial_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filial.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ),
    sa.PrimaryKeyConstraint('receita_id', 'filial_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receita_filial')
    op.drop_table('operacao')
    op.drop_table('usuario')
    op.drop_table('receita')
    op.drop_table('mixproduto')
    op.drop_table('inventario')
    op.drop_table('estoque')
    op.drop_table('produto')
    op.drop_table('cliente')
    op.drop_table('funcao')
    op.drop_table('fornecedor')
    op.drop_table('filial')
    # ### end Alembic commands ###
