"""empty message

Revision ID: 34ded3d7af89
Revises: 7c84ac10726d
Create Date: 2023-11-08 15:27:43.890073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34ded3d7af89'
down_revision = '7c84ac10726d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mixproduto_receita',
    sa.Column('mixproduto_id', sa.Integer(), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mixproduto_id'], ['mixproduto.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ),
    sa.PrimaryKeyConstraint('mixproduto_id', 'receita_id')
    )
    op.drop_table('receita_produto')
    op.add_column('mixproduto_filial', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mixproduto_filial', 'id')
    op.create_table('receita_produto',
    sa.Column('receita_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name='receita_produto_ibfk_1'),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], name='receita_produto_ibfk_2'),
    sa.PrimaryKeyConstraint('receita_id', 'produto_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('mixproduto_receita')
    # ### end Alembic commands ###
