"""empty message

Revision ID: 38601536d11a
Revises: 23bd11214090
Create Date: 2023-11-22 14:42:02.528196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38601536d11a'
down_revision = '23bd11214090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mixproduto_produto', sa.Column('quantidade', sa.Float(), nullable=False))
    op.drop_column('quantidade_mix_produtos', 'quantidade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quantidade_mix_produtos', sa.Column('quantidade', mysql.FLOAT(), nullable=True))
    op.drop_column('mixproduto_produto', 'quantidade')
    # ### end Alembic commands ###
