"""empty message

Revision ID: 3963fc6b6d82
Revises: 20b3cd41c17b
Create Date: 2023-11-22 16:08:38.252543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3963fc6b6d82'
down_revision = '20b3cd41c17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producao', sa.Column('mix_id', sa.Integer(), nullable=False))
    op.drop_constraint('producao_ibfk_2', 'producao', type_='foreignkey')
    op.create_foreign_key(None, 'producao', 'mixproduto', ['mix_id'], ['id'])
    op.drop_column('producao', 'mixproduto_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producao', sa.Column('mixproduto_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'producao', type_='foreignkey')
    op.create_foreign_key('producao_ibfk_2', 'producao', 'mixproduto', ['mixproduto_id'], ['id'])
    op.drop_column('producao', 'mix_id')
    # ### end Alembic commands ###
