"""empty message

Revision ID: 4c53f0823e64
Revises: 87838bd086e5
Create Date: 2023-11-17 18:38:00.354055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c53f0823e64'
down_revision = '87838bd086e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedido', 'cliente_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('pedido', 'fornecedor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('pedidoproducao', 'filial_pdv',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('pedidoproducao', 'mixproduto_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidoproducao', 'mixproduto_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('pedidoproducao', 'filial_pdv',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('pedido', 'fornecedor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('pedido', 'cliente_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
