"""empty message

Revision ID: 4d2357e99f40
Revises: 62c4d300fb37
Create Date: 2023-11-02 12:53:08.342464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d2357e99f40'
down_revision = '62c4d300fb37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receita_produto',
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ),
    sa.PrimaryKeyConstraint('receita_id', 'produto_id')
    )
    op.drop_table('mixproduto_produto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mixproduto_produto',
    sa.Column('mixproduto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mixproduto_id'], ['mixproduto.id'], name='mixproduto_produto_ibfk_1'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name='mixproduto_produto_ibfk_2'),
    sa.PrimaryKeyConstraint('mixproduto_id', 'produto_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('receita_produto')
    # ### end Alembic commands ###
