"""empty message

Revision ID: 4ead7ac5d3eb
Revises: 35a6ada42184
Create Date: 2023-09-07 00:35:15.232169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ead7ac5d3eb'
down_revision = '35a6ada42184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'filial_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('receita_produto', sa.Column('quantidade', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receita_produto', 'quantidade')
    op.alter_column('cliente', 'filial_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
