"""empty message

Revision ID: 60728dafb7e1
Revises: e3d90a6ef2ba
Create Date: 2023-10-31 18:39:21.115051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60728dafb7e1'
down_revision = 'e3d90a6ef2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('estoque_ibfk_1', 'estoque', type_='foreignkey')
    op.drop_column('estoque', 'produto_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estoque', sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('estoque_ibfk_1', 'estoque', 'produto', ['produto_id'], ['id'])
    # ### end Alembic commands ###
