"""empty message

Revision ID: 62617f01ffa7
Revises: 4211376fb5f2
Create Date: 2023-09-07 17:57:27.343126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62617f01ffa7'
down_revision = '4211376fb5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidoproducao', 'produto_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('pedidoproducao', 'receita_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidoproducao', 'receita_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('pedidoproducao', 'produto_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
