"""empty message

Revision ID: 637764828099
Revises: e7e96ec6d97a
Create Date: 2023-11-05 10:25:29.838535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '637764828099'
down_revision = 'e7e96ec6d97a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidoproducao', sa.Column('producao_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pedidoproducao', 'producao', ['producao_id'], ['id'])
    op.drop_column('producao', 'pedidosprod_id')
    op.drop_column('producao', 'usuario_id')
    op.drop_column('producao', 'pedidoproducao_id')
    op.add_column('produto', sa.Column('inventario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produto', 'inventario', ['inventario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.drop_column('produto', 'inventario_id')
    op.add_column('producao', sa.Column('pedidoproducao_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('producao', sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('producao', sa.Column('pedidosprod_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pedidoproducao', type_='foreignkey')
    op.drop_column('pedidoproducao', 'producao_id')
    # ### end Alembic commands ###
