"""empty message

Revision ID: 6ab84f65d843
Revises: 08190411f584
Create Date: 2023-11-22 19:00:45.178922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ab84f65d843'
down_revision = '08190411f584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidoproducao_filial',
    sa.Column('pedidoproducao_id', sa.Integer(), nullable=False),
    sa.Column('filial_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filial.id'], ),
    sa.ForeignKeyConstraint(['pedidoproducao_id'], ['pedidoproducao.id'], ),
    sa.PrimaryKeyConstraint('pedidoproducao_id', 'filial_id')
    )
    op.drop_table('mixproduto_filial')
    op.drop_constraint('mixproduto_ibfk_5', 'mixproduto', type_='foreignkey')
    op.drop_column('mixproduto', 'filial_id')
    op.drop_column('mixproduto', 'situacao')
    op.add_column('pedidoproducao', sa.Column('situacao', sa.String(length=50), nullable=False))
    op.drop_constraint('pedidoproducao_ibfk_3', 'pedidoproducao', type_='foreignkey')
    op.drop_constraint('pedidoproducao_ibfk_2', 'pedidoproducao', type_='foreignkey')
    op.drop_column('pedidoproducao', 'filial_pdv')
    op.drop_column('pedidoproducao', 'receita_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidoproducao', sa.Column('receita_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pedidoproducao', sa.Column('filial_pdv', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pedidoproducao_ibfk_2', 'pedidoproducao', 'filial', ['filial_pdv'], ['id'])
    op.create_foreign_key('pedidoproducao_ibfk_3', 'pedidoproducao', 'receita', ['receita_id'], ['id'])
    op.drop_column('pedidoproducao', 'situacao')
    op.add_column('mixproduto', sa.Column('situacao', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('mixproduto', sa.Column('filial_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('mixproduto_ibfk_5', 'mixproduto', 'filial', ['filial_id'], ['id'], ondelete='CASCADE')
    op.create_table('mixproduto_filial',
    sa.Column('mixproduto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filial_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qtde_produzida', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['filial_id'], ['filial.id'], name='mixproduto_filial_ibfk_1'),
    sa.ForeignKeyConstraint(['mixproduto_id'], ['mixproduto.id'], name='mixproduto_filial_ibfk_2'),
    sa.PrimaryKeyConstraint('mixproduto_id', 'filial_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('pedidoproducao_filial')
    # ### end Alembic commands ###
