"""empty message

Revision ID: 6b3e99701d63
Revises: e664965b0dfb
Create Date: 2023-11-16 23:03:02.414287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b3e99701d63'
down_revision = 'e664965b0dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quantidade_mix_produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('mix_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mix_id'], ['mixproduto.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('mixproduto', 'quantidade')
    op.drop_column('mixproduto_produto', 'qtde_produto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mixproduto_produto', sa.Column('qtde_produto', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('mixproduto', sa.Column('quantidade', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('quantidade_mix_produtos')
    # ### end Alembic commands ###
