"""empty message

Revision ID: 6b528bebf59e
Revises: 89deef429817
Create Date: 2023-08-13 03:59:11.242105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b528bebf59e'
down_revision = '89deef429817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidoproducao', 'receita_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidoproducao', 'receita_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
