"""empty message

Revision ID: 7bf4f9f29846
Revises: 34ded3d7af89
Create Date: 2023-11-09 02:23:39.275986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bf4f9f29846'
down_revision = '34ded3d7af89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mixproduto_produto',
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('mixproduto_id', sa.Integer(), nullable=False),
    sa.Column('qtde_produto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mixproduto_id'], ['mixproduto.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('produto_id', 'mixproduto_id')
    )
    op.drop_table('mixproduto_receita')
    op.drop_constraint('mixproduto_ibfk_4', 'mixproduto', type_='foreignkey')
    op.create_foreign_key(None, 'mixproduto', 'receita', ['receita_id'], ['id'])
    op.add_column('mixproduto_filial', sa.Column('qtde_produzida', sa.Integer(), nullable=True))
    op.drop_column('mixproduto_filial', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mixproduto_filial', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('mixproduto_filial', 'qtde_produzida')
    op.drop_constraint(None, 'mixproduto', type_='foreignkey')
    op.create_foreign_key('mixproduto_ibfk_4', 'mixproduto', 'receita', ['receita_id'], ['id'], ondelete='CASCADE')
    op.create_table('mixproduto_receita',
    sa.Column('mixproduto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receita_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mixproduto_id'], ['mixproduto.id'], name='mixproduto_receita_ibfk_1'),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], name='mixproduto_receita_ibfk_2'),
    sa.PrimaryKeyConstraint('mixproduto_id', 'receita_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('mixproduto_produto')
    # ### end Alembic commands ###
