"""empty message

Revision ID: 7c84ac10726d
Revises: 637764828099
Create Date: 2023-11-07 01:57:57.707252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c84ac10726d'
down_revision = '637764828099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estoque', sa.Column('fornecedor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'estoque', 'fornecedor', ['fornecedor_id'], ['id'])
    op.add_column('pedido', sa.Column('fornecedor_id', sa.Integer(), nullable=True))
    op.drop_constraint('pedido_ibfk_3', 'pedido', type_='foreignkey')
    op.drop_constraint('pedido_ibfk_2', 'pedido', type_='foreignkey')
    op.create_foreign_key(None, 'pedido', 'fornecedor', ['fornecedor_id'], ['id'])
    op.drop_column('pedido', 'produto_id')
    op.drop_column('pedido', 'fornecedor')
    op.add_column('produto', sa.Column('pedido_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produto', 'pedido', ['pedido_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.drop_column('produto', 'pedido_id')
    op.add_column('pedido', sa.Column('fornecedor', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pedido', sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pedido', type_='foreignkey')
    op.create_foreign_key('pedido_ibfk_2', 'pedido', 'fornecedor', ['fornecedor'], ['id'])
    op.create_foreign_key('pedido_ibfk_3', 'pedido', 'produto', ['produto_id'], ['id'])
    op.drop_column('pedido', 'fornecedor_id')
    op.drop_constraint(None, 'estoque', type_='foreignkey')
    op.drop_column('estoque', 'fornecedor_id')
    # ### end Alembic commands ###
