"""empty message

Revision ID: 860784709ac5
Revises: 4d2357e99f40
Create Date: 2023-11-03 17:55:50.893129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860784709ac5'
down_revision = '4d2357e99f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_producao', sa.DateTime(), nullable=False),
    sa.Column('qtde_produzida', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('qr_code', sa.String(length=50), nullable=True),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('mix_produto_id', sa.Integer(), nullable=False),
    sa.Column('filial_id', sa.Integer(), nullable=False),
    sa.Column('pedidoproducao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filial.id'], ),
    sa.ForeignKeyConstraint(['mix_produto_id'], ['mixproduto.id'], ),
    sa.ForeignKeyConstraint(['pedidoproducao_id'], ['pedidoproducao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usuario', sa.Column('producao_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuario', 'producao', ['producao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'producao_id')
    op.drop_table('producao')
    # ### end Alembic commands ###
