"""empty message

Revision ID: 89deef429817
Revises: f55a25ea213b
Create Date: 2023-08-11 16:25:54.524618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89deef429817'
down_revision = 'f55a25ea213b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('filial', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('fornecedor', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('mixproduto', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_constraint('mixproduto_ibfk_1', 'mixproduto', type_='foreignkey')
    op.create_foreign_key(None, 'mixproduto', 'cliente', ['cliente_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mixproduto', type_='foreignkey')
    op.create_foreign_key('mixproduto_ibfk_1', 'mixproduto', 'cliente', ['cliente_id'], ['id'])
    op.alter_column('mixproduto', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('fornecedor', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('filial', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('cliente', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###
