"""empty message

Revision ID: 8d1242e8572c
Revises: 3963fc6b6d82
Create Date: 2023-11-22 16:10:08.065357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d1242e8572c'
down_revision = '3963fc6b6d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'producao', 'mixproduto', ['mix_id'], ['id'])
    op.drop_column('producao', 'mixproduto_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producao', sa.Column('mixproduto_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'producao', type_='foreignkey')
    # ### end Alembic commands ###
