"""empty message

Revision ID: 9252d692b572
Revises: 4ead7ac5d3eb
Create Date: 2023-09-07 15:43:59.880544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9252d692b572'
down_revision = '4ead7ac5d3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receita', sa.Column('produto_quantidades', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receita', 'produto_quantidades')
    # ### end Alembic commands ###
