"""empty message

Revision ID: 9b80e7913cf1
Revises: 
Create Date: 2023-10-31 13:18:53.584057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b80e7913cf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('endereco', sa.String(length=150), nullable=False),
    sa.Column('bairro', sa.String(length=20), nullable=False),
    sa.Column('cidade', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('responsavel', sa.String(length=50), nullable=False),
    sa.Column('whatsapp', sa.String(length=50), nullable=False),
    sa.Column('cnpj', sa.String(length=17), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('valor_ultima_compra', sa.Float(), nullable=False),
    sa.Column('quantidade_minima', sa.Integer(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('quantidade_atual', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('endereco', sa.String(length=150), nullable=False),
    sa.Column('bairro', sa.String(length=20), nullable=False),
    sa.Column('cidade', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('responsavel', sa.String(length=50), nullable=False),
    sa.Column('whatsapp', sa.String(length=50), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('filial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('endereco', sa.String(length=150), nullable=False),
    sa.Column('bairro', sa.String(length=20), nullable=False),
    sa.Column('cidade', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('responsavel', sa.String(length=50), nullable=False),
    sa.Column('whatsapp', sa.String(length=50), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=250), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('compra_unid', sa.Integer(), nullable=False),
    sa.Column('peso_pcte', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('valor', sa.Numeric(), nullable=False),
    sa.Column('custo_ultima_compra', sa.Float(), nullable=False),
    sa.Column('whatsapp', sa.String(length=50), nullable=False),
    sa.Column('qrcode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('estoque_minimo', sa.Integer(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('api_key', sa.String(length=100), nullable=True),
    sa.Column('empresa', sa.Integer(), nullable=True),
    sa.Column('cargo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cargo'], ['funcao.id'], ),
    sa.ForeignKeyConstraint(['empresa'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=True),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.String(length=80), nullable=True),
    sa.Column('obs', sa.String(length=120), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('filial_pdv', sa.Integer(), nullable=True),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['filial_pdv'], ['filial.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qtde_pedido', sa.Integer(), nullable=True),
    sa.Column('data_pedido', sa.DateTime(), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=False),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['fornecedor'], ['fornecedor.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receita',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao_mix', sa.Text(), nullable=False),
    sa.Column('modo_preparo', sa.Text(), nullable=False),
    sa.Column('departamento', sa.String(length=50), nullable=False),
    sa.Column('rend_kg', sa.Float(), nullable=False),
    sa.Column('rend_unid', sa.Float(), nullable=False),
    sa.Column('validade', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reposicao_estoque',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidoproducao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=False),
    sa.Column('qtde_pedido', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('receita_id', sa.Integer(), nullable=True),
    sa.Column('filial_pdv', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['filial_pdv'], ['filial.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mixproduto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cod_prod_mix', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=False),
    sa.Column('cadastrado_em', sa.Date(), nullable=False),
    sa.Column('atualizado_em', sa.Date(), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('filial_id', sa.Integer(), nullable=False),
    sa.Column('usuarios', sa.Integer(), nullable=False),
    sa.Column('pedidosprod_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filial.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedidosprod_id'], ['pedidoproducao.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuarios'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mixproduto_filial',
    sa.Column('mixproduto_id', sa.Integer(), nullable=False),
    sa.Column('filial_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filial.id'], ),
    sa.ForeignKeyConstraint(['mixproduto_id'], ['mixproduto.id'], ),
    sa.PrimaryKeyConstraint('mixproduto_id', 'filial_id')
    )
    op.create_table('mixproduto_produto',
    sa.Column('mixproduto_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mixproduto_id'], ['mixproduto.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('mixproduto_id', 'produto_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mixproduto_produto')
    op.drop_table('mixproduto_filial')
    op.drop_table('mixproduto')
    op.drop_table('pedidoproducao')
    op.drop_table('reposicao_estoque')
    op.drop_table('receita')
    op.drop_table('pedido')
    op.drop_table('inventario')
    op.drop_table('usuario')
    op.drop_table('produto')
    op.drop_table('filial')
    op.drop_table('funcao')
    op.drop_table('fornecedor')
    op.drop_table('estoque')
    op.drop_table('cliente')
    # ### end Alembic commands ###
