"""empty message

Revision ID: a540b10ce09b
Revises: 
Create Date: 2023-10-11 23:35:21.111114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a540b10ce09b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reposicao_estoque',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.String(length=50), nullable=False),
    sa.Column('produto_id', sa.String(length=100), nullable=False),
    sa.Column('qtde', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('compra', 'producao', name='tipoenum'), nullable=False),
    sa.Column('estoque_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estoque_id'], ['estoque.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receita',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao_mix', sa.Text(), nullable=False),
    sa.Column('modo_preparo', sa.Text(), nullable=False),
    sa.Column('departamento', sa.String(length=50), nullable=False),
    sa.Column('rend_kg', sa.Float(), nullable=False),
    sa.Column('rend_unid', sa.Float(), nullable=False),
    sa.Column('validade', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mixproduto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cod_prod_mix', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('cadastrado_em', sa.Date(), nullable=False),
    sa.Column('atualizado_em', sa.Date(), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('filial_id', sa.Integer(), nullable=False),
    sa.Column('usuarios', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filial.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuarios'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidoproducao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=False),
    sa.Column('qtde_pedido', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('filial_pdv', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filial_pdv'], ['filial.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receita_produto',
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], )
    )
    op.create_table('mixproduto_filial',
    sa.Column('mixproduto_id', sa.Integer(), nullable=False),
    sa.Column('filial_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filial.id'], ),
    sa.ForeignKeyConstraint(['mixproduto_id'], ['mixproduto.id'], ),
    sa.PrimaryKeyConstraint('mixproduto_id', 'filial_id')
    )
    op.add_column('cliente', sa.Column('filial_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cliente', 'filial', ['filial_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cliente', type_='foreignkey')
    op.drop_column('cliente', 'filial_id')
    op.drop_table('mixproduto_filial')
    op.drop_table('receita_produto')
    op.drop_table('pedidoproducao')
    op.drop_table('mixproduto')
    op.drop_table('ingredientes')
    op.drop_table('receita')
    op.drop_table('operacao')
    op.drop_table('reposicao_estoque')
    # ### end Alembic commands ###
