"""empty message

Revision ID: a731ed8b2349
Revises: 04a24e7ccca0
Create Date: 2023-11-25 21:42:40.324271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a731ed8b2349'
down_revision = '04a24e7ccca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('produto_ibfk_4', 'produto', type_='foreignkey')
    op.add_column('pedido', sa.Column('produto_id', sa.Integer(), nullable=True))
    op.alter_column('pedido', 'data_entrega',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_unique_constraint(None, 'pedido', ['produto_id'])
    op.create_foreign_key(None, 'pedido', 'produto', ['produto_id'], ['id'])

    op.drop_column('produto', 'pedido_id')
    op.alter_column('quantidade_mix_produtos', 'produto_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('quantidade_mix_produtos', 'mix_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quantidade_mix_produtos', 'mix_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('quantidade_mix_produtos', 'produto_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('produto', sa.Column('pedido_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('produto_ibfk_4', 'produto', 'pedido', ['pedido_id'], ['id'])
    op.drop_constraint(None, 'pedido', type_='foreignkey')
    op.drop_constraint(None, 'pedido', type_='unique')
    op.alter_column('pedido', 'data_entrega',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('pedido', 'produto_id')
    # ### end Alembic commands ###
