"""empty message

Revision ID: af5d13b9f5a1
Revises: 3426b47f968c
Create Date: 2023-08-01 01:43:09.066173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5d13b9f5a1'
down_revision = '3426b47f968c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filial', sa.Column('receita', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'filial', 'receita', ['receita'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filial', type_='foreignkey')
    op.drop_column('filial', 'receita')
    # ### end Alembic commands ###
