"""empty message

Revision ID: b282032c0b7e
Revises: a2f5ad22d4ef
Create Date: 2023-08-02 23:07:37.949311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b282032c0b7e'
down_revision = 'a2f5ad22d4ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidoproducao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=True),
    sa.Column('data_entrega', sa.Date(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('filial_pdv', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filial_pdv'], ['filial.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('estoque', sa.Column('quantidade_op', sa.Integer(), nullable=True))
    op.drop_column('estoque', 'quantidade_estoque')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estoque', sa.Column('quantidade_estoque', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('estoque', 'quantidade_op')
    op.drop_table('pedidoproducao')
    # ### end Alembic commands ###
