"""empty message

Revision ID: b3be35dc39b7
Revises: f2c9f1b392b4
Create Date: 2023-10-20 13:33:36.613804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3be35dc39b7'
down_revision = 'f2c9f1b392b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receita_cliente')
    op.drop_constraint('cliente_ibfk_2', 'cliente', type_='foreignkey')
    op.drop_column('cliente', 'receita')
    op.add_column('pedidoproducao', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pedidoproducao', 'cliente', ['cliente_id'], ['id'])
    op.add_column('receita', sa.Column('cliente_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'receita', 'cliente', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receita', type_='foreignkey')
    op.drop_column('receita', 'cliente_id')
    op.drop_constraint(None, 'pedidoproducao', type_='foreignkey')
    op.drop_column('pedidoproducao', 'cliente_id')
    op.add_column('cliente', sa.Column('receita', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cliente_ibfk_2', 'cliente', 'receita', ['receita'], ['id'])
    op.create_table('receita_cliente',
    sa.Column('receita_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='receita_cliente_ibfk_1'),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], name='receita_cliente_ibfk_2'),
    sa.PrimaryKeyConstraint('receita_id', 'cliente_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
