"""empty message

Revision ID: b586d2beb83f
Revises: 4c53f0823e64
Create Date: 2023-11-17 18:51:59.782311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b586d2beb83f'
down_revision = '4c53f0823e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedido', 'cliente_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('pedido', 'fornecedor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('pedidoproducao', 'filial_pdv',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('pedidoproducao', 'mixproduto_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('quantidade_mix_produtos', 'produto_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('quantidade_mix_produtos', 'mix_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quantidade_mix_produtos', 'mix_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('quantidade_mix_produtos', 'produto_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('pedidoproducao', 'mixproduto_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('pedidoproducao', 'filial_pdv',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('pedido', 'fornecedor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('pedido', 'cliente_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
