"""empty message

Revision ID: baa0b16084ca
Revises: 9bf768cf72f5
Create Date: 2023-11-28 17:26:23.688681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'baa0b16084ca'
down_revision = '9bf768cf72f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produto', 'custo_ultima_compra',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produto', 'custo_ultima_compra',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
