"""empty message

Revision ID: c40637b5292f
Revises: b282032c0b7e
Create Date: 2023-08-03 15:24:38.683659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c40637b5292f'
down_revision = 'b282032c0b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedido', 'tipo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('tipo', mysql.ENUM('compra', 'producao'), nullable=False))
    # ### end Alembic commands ###
