"""empty message

Revision ID: c7ebd51e7cd9
Revises: 297089e43cca
Create Date: 2023-11-25 23:19:08.589085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7ebd51e7cd9'
down_revision = '297089e43cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('produto_id', table_name='pedido')
    op.drop_constraint('pedido_ibfk_2', 'pedido', type_='foreignkey')
    op.drop_constraint('pedido_ibfk_3', 'pedido', type_='foreignkey')
    op.drop_constraint('pedido_ibfk_1', 'pedido', type_='foreignkey')
    op.drop_column('pedido', 'fornecedor_id')
    op.drop_column('pedido', 'produto_id')
    op.drop_column('pedido', 'cliente_id')
    op.drop_constraint('produto_ibfk_4', 'produto', type_='foreignkey')
    op.drop_column('produto', 'pedido_id')
    op.alter_column('quantidade_mix_produtos', 'produto_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('quantidade_mix_produtos', 'mix_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quantidade_mix_produtos', 'mix_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('quantidade_mix_produtos', 'produto_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('produto', sa.Column('pedido_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('produto_ibfk_4', 'produto', 'pedido', ['pedido_id'], ['id'])
    op.add_column('pedido', sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pedido', sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pedido', sa.Column('fornecedor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pedido_ibfk_1', 'pedido', 'cliente', ['cliente_id'], ['id'])
    op.create_foreign_key('pedido_ibfk_3', 'pedido', 'produto', ['produto_id'], ['id'])
    op.create_foreign_key('pedido_ibfk_2', 'pedido', 'fornecedor', ['fornecedor_id'], ['id'])
    op.create_index('produto_id', 'pedido', ['produto_id'], unique=False)
    # ### end Alembic commands ###
