"""empty message

Revision ID: ca648867e6b0
Revises: 860784709ac5
Create Date: 2023-11-03 20:41:29.573721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca648867e6b0'
down_revision = '860784709ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('mixproduto')
    op.add_column('mixproduto_filial', sa.Column('mixproduto_id', sa.Integer(), nullable=False))
    op.drop_constraint('mixproduto_filial_ibfk_2', 'mixproduto_filial', type_='foreignkey')
    op.create_foreign_key(None, 'mixproduto_filial', 'mixproduto', ['mixproduto_id'], ['id'])
    op.drop_column('mixproduto_filial', 'mixproduto_id')
    op.add_column('producao', sa.Column('mix_produto_id', sa.Integer(), nullable=False))
    op.drop_constraint('producao_ibfk_2', 'producao', type_='foreignkey')
    op.create_foreign_key(None, 'producao', 'mixproduto', ['mix_produto_id'], ['id'])
    op.drop_column('producao', 'mixproduto_id')
    # ### end Alembic commands ###
    op.create_table('mixproduto',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('cod_prod_mix', sa.Integer(), nullable=True),
                    sa.Column('status', sa.Integer(), nullable=True),
                    sa.Column('situacao', sa.String(length=50), nullable=False),
                    sa.Column('cadastrado_em', sa.Date(), nullable=False),
                    sa.Column('atualizado_em', sa.Date(), nullable=False),
                    sa.Column('receita_id', sa.Integer(), nullable=False),
                    sa.Column('filial_id', sa.Integer(), nullable=False),
                    sa.Column('usuarios', sa.Integer(), nullable=False),
                    sa.Column('pedidosprod_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['filial_id'], ['filial.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['pedidosprod_id'], ['pedidoproducao.id'], ),
                    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['usuarios'], ['usuario.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producao', sa.Column('mixproduto_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'producao', type_='foreignkey')
    op.create_foreign_key('producao_ibfk_2', 'producao', 'mixproduto', ['mixproduto_id'], ['id'])
    op.drop_column('producao', 'mix_produto_id')
    op.add_column('mixproduto_filial', sa.Column('mixproduto_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mixproduto_filial', type_='foreignkey')
    op.create_foreign_key('mixproduto_filial_ibfk_2', 'mixproduto_filial', 'mixproduto', ['mixproduto_id'], ['id'])
    op.drop_column('mixproduto_filial', 'mix_produto_id')
    op.create_table('mixproduto',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cod_prod_mix', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('situacao', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('cadastrado_em', sa.DATE(), nullable=False),
    sa.Column('atualizado_em', sa.DATE(), nullable=False),
    sa.Column('receita_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filial_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuarios', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pedidosprod_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filial.id'], name='mixproduto_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedidosprod_id'], ['pedidoproducao.id'], name='mixproduto_ibfk_2'),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], name='mixproduto_ibfk_3', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuarios'], ['usuario.id'], name='mixproduto_ibfk_4'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('mix_produto')
    # ### end Alembic commands ###
