"""empty message

Revision ID: e3d90a6ef2ba
Revises: 9b80e7913cf1
Create Date: 2023-10-31 13:23:45.426185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d90a6ef2ba'
down_revision = '9b80e7913cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque_filial',
    sa.Column('estoque_id', sa.Integer(), nullable=False),
    sa.Column('filial_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estoque_id'], ['estoque.id'], ),
    sa.ForeignKeyConstraint(['filial_id'], ['filial.id'], ),
    sa.PrimaryKeyConstraint('estoque_id', 'filial_id')
    )
    op.add_column('estoque', sa.Column('produto_id', sa.Integer(), nullable=False))
    op.add_column('estoque', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'estoque', 'produto', ['produto_id'], ['id'])
    op.create_foreign_key(None, 'estoque', 'cliente', ['cliente_id'], ['id'])
    op.add_column('produto', sa.Column('estoque_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'produto', 'estoque', ['estoque_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.drop_column('produto', 'estoque_id')
    op.drop_constraint(None, 'estoque', type_='foreignkey')
    op.drop_constraint(None, 'estoque', type_='foreignkey')
    op.drop_column('estoque', 'cliente_id')
    op.drop_column('estoque', 'produto_id')
    op.drop_table('estoque_filial')
    # ### end Alembic commands ###
