"""empty message

Revision ID: e664965b0dfb
Revises: 4538d45fe75b
Create Date: 2023-11-16 17:12:02.913490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e664965b0dfb'
down_revision = '4538d45fe75b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mixproduto_filial')
    op.alter_column('mixproduto', 'atualizado_em',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint('mixproduto_ibfk_1', 'mixproduto', type_='foreignkey')
    op.drop_column('mixproduto', 'filial_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mixproduto', sa.Column('filial_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('mixproduto_ibfk_1', 'mixproduto', 'filial', ['filial_id'], ['id'], ondelete='CASCADE')
    op.alter_column('mixproduto', 'atualizado_em',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_table('mixproduto_filial',
    sa.Column('mixproduto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filial_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qtde_produzida', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['filial_id'], ['filial.id'], name='mixproduto_filial_ibfk_1'),
    sa.ForeignKeyConstraint(['mixproduto_id'], ['mixproduto.id'], name='mixproduto_filial_ibfk_2'),
    sa.PrimaryKeyConstraint('mixproduto_id', 'filial_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
