"""empty message

Revision ID: e7e96ec6d97a
Revises: ec4e93432cda
Create Date: 2023-11-05 10:14:59.024509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7e96ec6d97a'
down_revision = 'ec4e93432cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'producao', 'mixproduto', ['mixproduto_id'], ['id'])
    op.create_foreign_key(None, 'producao', 'pedidoproducao', ['pedidosprod_id'], ['id'])
    op.drop_column('producao', 'pedidoproducao_id')
    op.drop_column('producao', 'usuario_id')
    op.add_column('produto', sa.Column('inventario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produto', 'inventario', ['inventario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.drop_column('produto', 'inventario_id')
    op.add_column('producao', sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('producao', sa.Column('pedidoproducao_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'producao', type_='foreignkey')
    op.drop_constraint(None, 'producao', type_='foreignkey')
    # ### end Alembic commands ###
