"""empty message

Revision ID: f2c9f1b392b4
Revises: 475ce0079134
Create Date: 2023-10-12 04:11:27.625704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2c9f1b392b4'
down_revision = '475ce0079134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material')
    op.add_column('ingredientes', sa.Column('produto_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ingredientes', 'produto', ['produto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredientes', type_='foreignkey')
    op.drop_column('ingredientes', 'produto_id')
    op.create_table('material',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('quantidade', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
