"""empty message

Revision ID: f55a25ea213b
Revises: 27b44cd00888
Create Date: 2023-08-10 01:48:29.543790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55a25ea213b'
down_revision = '27b44cd00888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'receita_produto', ['receita_id'])
    op.create_unique_constraint(None, 'receita_produto', ['produto_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receita_produto', type_='unique')
    op.drop_constraint(None, 'receita_produto', type_='unique')
    # ### end Alembic commands ###
